
spring:
  application:
    name: springcloudstream
  cloud:
    instance-count: 2
    instance-index: 0
    stream:
      kafka:
        binder:
          brokers: localhost:9092
          zk-nodes: localhost:2181
      bindings:
        input:
          destination: russell
          contentType: application/json
          consumer:
            partitioned: true

        output:
          destination: russell
          contentType: application/json
